default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: map_pin_user
  password: myPass123
  host: localhost
  port: 5432

development:
  <<: *default
  database: mappinapp_development

test:
  <<: *default
  database: mappinapp_test

production:
  <<: *default
  database: mappinapp_production